# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_auto_20170207_1302'),
        ('rango', '0005_auto_20170207_2054'),
    ]

    operations = [
    ]
